from playwright.sync_api import sync_playwright
with sync_playwright() as p:
 browser=p.chromium.launch(args=['--use-fake-device-for-media-stream','--use-fake-ui-for-media-stream'])
 page=browser.new_page()
 page.goto('http://localhost:8000')
 page.locator('#samson').click()
 response=page.request.get('https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.21/vision_bundle.mjs')
 print('CDN module status:',response.status)
 assert response.ok
 page.locator('#start').click()
 page.wait_for_function("document.querySelector('#cameraState').textContent === '\\uCE74\\uBA54\\uB77C \\uC5F0\\uACB0\\uB428'",timeout=90000)
 assert page.evaluate("document.querySelector('video').srcObject.active")
 assert page.locator('#error').is_hidden()
 print('PASS: real MediaPipe initialized with simulated camera')
 page.close()
 page=browser.new_page()
 page.route('**/vision_bundle.mjs',lambda route:route.abort())
 page.goto('http://localhost:8000')
 page.locator('#samson').click()
 page.locator('#start').click()
 page.locator('#error').wait_for(state='visible')
 assert page.evaluate("document.querySelector('video').srcObject.active")
 assert page.locator('#placeholder').is_hidden()
 page.locator('#next').click()
 assert page.locator('#result').is_visible()
 page.locator('#quit').click()
 assert page.evaluate("document.querySelector('video').srcObject === null")
 print('PASS: module failure preserves preview; manual progression and camera shutdown work')
 browser.close()
