from playwright.sync_api import sync_playwright
with sync_playwright() as p:
    browser=p.chromium.launch()
    page=browser.new_page(viewport={"width":1440,"height":1000})
    errors=[]
    page.on('pageerror',lambda e:errors.append(str(e)))
    page.goto('http://127.0.0.1:8000')
    page.locator('#samson').click()
    page.locator('#next').click()
    assert page.locator('#result').is_visible()
    page.locator('#next').click()
    assert page.locator('#resultBadge').is_visible()
    page.locator('#next').click()
    assert page.locator('#capture').is_visible()
    page.locator('#next').click()
    page.wait_for_timeout(8200)
    assert page.locator('#capture').is_visible()
    page.locator('#next').click()
    page.locator('#quit').click()
    page.wait_for_timeout(2100)
    assert page.locator('#ended').is_visible()
    page.locator('#restart').click()
    page.locator('#samson').click()
    page.locator('#start').click()
    page.locator('#error').wait_for(state='visible')
    assert page.locator('#next').is_enabled()
    values=page.evaluate("async () => { const {classifyThrow:c}=await import('./motion.js'); return [.5,1,2,3,5,7].map(s=>c(.1,s).score); }")
    assert values == [9,15,27,39,62,86],values
    page.screenshot(path='preview.png',full_page=True)
    page.set_viewport_size({"width":390,"height":844})
    assert page.evaluate('document.documentElement.scrollWidth <= innerWidth')
    assert not errors,errors
    print('PASS: transitions, skip, auto-return, exit, restart, camera failure fallback, scoring, mobile width, JS errors')
    browser.close()
